[package]
name = "advent2022"
version = "0.1.0"
edition = "2021"
authors = ["yopox <yopox@mailo.fr>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.10.5"

[profile.dev]
opt-level = 3